// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capabilities.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteCapability = `-- name: DeleteCapability :exec
DELETE FROM capabilities WHERE id = ?
`

func (q *Queries) DeleteCapability(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCapability, id)
	return err
}

const findCapability = `-- name: FindCapability :one
SELECT id, kind, name, version, description, author, source_type, source_uri, source_ref, trust_level, scope, status, requirements_json, manifest_path, manifest_json, hash, created_at, updated_at FROM capabilities WHERE kind = ? AND name = ? AND version = ? LIMIT 1
`

type FindCapabilityParams struct {
	Kind    string
	Name    string
	Version string
}

func (q *Queries) FindCapability(ctx context.Context, arg FindCapabilityParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, findCapability, arg.Kind, arg.Name, arg.Version)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Author,
		&i.SourceType,
		&i.SourceUri,
		&i.SourceRef,
		&i.TrustLevel,
		&i.Scope,
		&i.Status,
		&i.RequirementsJson,
		&i.ManifestPath,
		&i.ManifestJson,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapability = `-- name: GetCapability :one
SELECT id, kind, name, version, description, author, source_type, source_uri, source_ref, trust_level, scope, status, requirements_json, manifest_path, manifest_json, hash, created_at, updated_at FROM capabilities WHERE id = ?
`

func (q *Queries) GetCapability(ctx context.Context, id string) (Capability, error) {
	row := q.db.QueryRowContext(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Author,
		&i.SourceType,
		&i.SourceUri,
		&i.SourceRef,
		&i.TrustLevel,
		&i.Scope,
		&i.Status,
		&i.RequirementsJson,
		&i.ManifestPath,
		&i.ManifestJson,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT id, kind, name, version, description, author, source_type, source_uri, source_ref, trust_level, scope, status, requirements_json, manifest_path, manifest_json, hash, created_at, updated_at FROM capabilities WHERE status = ? ORDER BY kind, name
`

func (q *Queries) ListCapabilities(ctx context.Context, status string) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilities, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Author,
			&i.SourceType,
			&i.SourceUri,
			&i.SourceRef,
			&i.TrustLevel,
			&i.Scope,
			&i.Status,
			&i.RequirementsJson,
			&i.ManifestPath,
			&i.ManifestJson,
			&i.Hash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilitiesByKind = `-- name: ListCapabilitiesByKind :many
SELECT id, kind, name, version, description, author, source_type, source_uri, source_ref, trust_level, scope, status, requirements_json, manifest_path, manifest_json, hash, created_at, updated_at FROM capabilities WHERE kind = ? AND status = ? ORDER BY name
`

type ListCapabilitiesByKindParams struct {
	Kind   string
	Status string
}

func (q *Queries) ListCapabilitiesByKind(ctx context.Context, arg ListCapabilitiesByKindParams) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilitiesByKind, arg.Kind, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Author,
			&i.SourceType,
			&i.SourceUri,
			&i.SourceRef,
			&i.TrustLevel,
			&i.Scope,
			&i.Status,
			&i.RequirementsJson,
			&i.ManifestPath,
			&i.ManifestJson,
			&i.Hash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCapability = `-- name: UpsertCapability :exec
INSERT INTO capabilities
  (id, kind, name, version, description, author, source_type, source_uri, source_ref,
   trust_level, scope, status, requirements_json, manifest_path, manifest_json, hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  description       = excluded.description,
  author            = excluded.author,
  source_type       = excluded.source_type,
  source_uri        = excluded.source_uri,
  source_ref        = excluded.source_ref,
  trust_level       = excluded.trust_level,
  status            = excluded.status,
  requirements_json = excluded.requirements_json,
  manifest_path     = excluded.manifest_path,
  manifest_json     = excluded.manifest_json,
  hash              = excluded.hash,
  updated_at        = excluded.updated_at
`

type UpsertCapabilityParams struct {
	ID               string
	Kind             string
	Name             string
	Version          string
	Description      sql.NullString
	Author           sql.NullString
	SourceType       string
	SourceUri        sql.NullString
	SourceRef        sql.NullString
	TrustLevel       sql.NullString
	Scope            sql.NullString
	Status           string
	RequirementsJson sql.NullString
	ManifestPath     sql.NullString
	ManifestJson     string
	Hash             sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, upsertCapability,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Author,
		arg.SourceType,
		arg.SourceUri,
		arg.SourceRef,
		arg.TrustLevel,
		arg.Scope,
		arg.Status,
		arg.RequirementsJson,
		arg.ManifestPath,
		arg.ManifestJson,
		arg.Hash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
