// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql"
)

type Capability struct {
	ID               string
	Kind             string
	Name             string
	Version          string
	Description      sql.NullString
	Author           sql.NullString
	SourceType       string
	SourceUri        sql.NullString
	SourceRef        sql.NullString
	TrustLevel       sql.NullString
	Scope            sql.NullString
	Status           string
	RequirementsJson sql.NullString
	ManifestPath     sql.NullString
	ManifestJson     string
	Hash             sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type Message struct {
	ID        string
	SessionID string
	ParentID  sql.NullString
	Role      string
	Sequence  int64
	CreatedAt string
}

type MessageAttachment struct {
	ID        string
	MessageID string
	Direction string
	Name      string
	Uri       string
	MediaType sql.NullString
	SizeBytes sql.NullInt64
	Sha256    sql.NullString
	CreatedAt string
}

type MessagePart struct {
	ID          string
	MessageID   string
	Sequence    int64
	Type        string
	ContentJson string
}

type SandboxDef struct {
	ID           string
	Name         string
	Provider     string
	BaseImageRef sql.NullString
	PolicyRef    sql.NullString
	CreatedAt    string
}

type SandboxInstance struct {
	ID                 string
	SandboxDefID       string
	WorkspaceID        string
	Owner              string
	RunAs              sql.NullString
	ProviderSandboxID  sql.NullString
	PolicySnapshotJson sql.NullString
	Status             string
	CreatedAt          string
	UpdatedAt          string
	LastSeenAt         sql.NullString
}

type Session struct {
	ID                string
	SandboxInstanceID string
	Title             string
	Status            string
	CreatedBy         sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type User struct {
	ID         string
	Name       string
	Email      sql.NullString
	ExternalID sql.NullString
	Status     string
	CreatedAt  string
	UpdatedAt  string
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt string
}

type WorkspaceRef struct {
	WorkspaceID string
	Kind        string
	Slot        string
	Ref         string
	CreatedAt   string
}
