// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package dbq

import (
	"context"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id, name, created_at, updated_at) VALUES (?, ?, ?, ?)
`

type CreateProfileParams struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, created_at, updated_at FROM profiles WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByName = `-- name: GetProfileByName :one
SELECT id, name, created_at, updated_at FROM profiles WHERE name = ?
`

func (q *Queries) GetProfileByName(ctx context.Context, name string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByName, name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, created_at, updated_at FROM profiles ORDER BY name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileName = `-- name: UpdateProfileName :exec
UPDATE profiles SET name = ?, updated_at = ? WHERE id = ?
`

type UpdateProfileNameParams struct {
	Name      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateProfileName(ctx context.Context, arg UpdateProfileNameParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
