// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbq

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, session_id, parent_id, role, sequence, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID        string
	SessionID string
	ParentID  sql.NullString
	Role      string
	Sequence  int64
	CreatedAt string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.ParentID,
		arg.Role,
		arg.Sequence,
		arg.CreatedAt,
	)
	return err
}

const createMessageAttachment = `-- name: CreateMessageAttachment :exec
INSERT INTO message_attachments (id, message_id, direction, name, uri, media_type, size_bytes, sha256, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageAttachmentParams struct {
	ID        string
	MessageID string
	Direction string
	Name      string
	Uri       string
	MediaType sql.NullString
	SizeBytes sql.NullInt64
	Sha256    sql.NullString
	CreatedAt string
}

func (q *Queries) CreateMessageAttachment(ctx context.Context, arg CreateMessageAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createMessageAttachment,
		arg.ID,
		arg.MessageID,
		arg.Direction,
		arg.Name,
		arg.Uri,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.CreatedAt,
	)
	return err
}

const createMessagePart = `-- name: CreateMessagePart :exec
INSERT INTO message_parts (id, message_id, sequence, type, content_json)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessagePartParams struct {
	ID          string
	MessageID   string
	Sequence    int64
	Type        string
	ContentJson string
}

func (q *Queries) CreateMessagePart(ctx context.Context, arg CreateMessagePartParams) error {
	_, err := q.db.ExecContext(ctx, createMessagePart,
		arg.ID,
		arg.MessageID,
		arg.Sequence,
		arg.Type,
		arg.ContentJson,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, sandbox_instance_id, title, status, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID                string
	SandboxInstanceID string
	Title             string
	Status            string
	CreatedBy         sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.SandboxInstanceID,
		arg.Title,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, parent_id, role, sequence, created_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Role,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, sandbox_instance_id, title, status, created_by, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SandboxInstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessageAttachments = `-- name: ListMessageAttachments :many
SELECT id, message_id, direction, name, uri, media_type, size_bytes, sha256, created_at FROM message_attachments WHERE message_id = ?
`

func (q *Queries) ListMessageAttachments(ctx context.Context, messageID string) ([]MessageAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listMessageAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Direction,
			&i.Name,
			&i.Uri,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageParts = `-- name: ListMessageParts :many
SELECT id, message_id, sequence, type, content_json FROM message_parts WHERE message_id = ? ORDER BY sequence
`

func (q *Queries) ListMessageParts(ctx context.Context, messageID string) ([]MessagePart, error) {
	rows, err := q.db.QueryContext(ctx, listMessageParts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagePart
	for rows.Next() {
		var i MessagePart
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Sequence,
			&i.Type,
			&i.ContentJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, session_id, parent_id, role, sequence, created_at FROM messages WHERE session_id = ? ORDER BY sequence
`

func (q *Queries) ListMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Role,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsBySandbox = `-- name: ListSessionsBySandbox :many
SELECT id, sandbox_instance_id, title, status, created_by, created_at, updated_at FROM sessions WHERE sandbox_instance_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessionsBySandbox(ctx context.Context, sandboxInstanceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsBySandbox, sandboxInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.SandboxInstanceID,
			&i.Title,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
