// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbq

import (
	"context"
	"database/sql"
)

const createSandboxDef = `-- name: CreateSandboxDef :exec
INSERT INTO sandbox_defs (id, name, provider, base_image_ref, policy_ref, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSandboxDefParams struct {
	ID           string
	Name         string
	Provider     string
	BaseImageRef sql.NullString
	PolicyRef    sql.NullString
	CreatedAt    string
}

func (q *Queries) CreateSandboxDef(ctx context.Context, arg CreateSandboxDefParams) error {
	_, err := q.db.ExecContext(ctx, createSandboxDef,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.BaseImageRef,
		arg.PolicyRef,
		arg.CreatedAt,
	)
	return err
}

const createSandboxInstance = `-- name: CreateSandboxInstance :exec
INSERT INTO sandbox_instances
  (id, sandbox_def_id, workspace_id, owner, run_as, provider_sandbox_id,
   policy_snapshot_json, status, created_at, updated_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSandboxInstanceParams struct {
	ID                 string
	SandboxDefID       string
	WorkspaceID        string
	Owner              string
	RunAs              sql.NullString
	ProviderSandboxID  sql.NullString
	PolicySnapshotJson sql.NullString
	Status             string
	CreatedAt          string
	UpdatedAt          string
	LastSeenAt         sql.NullString
}

func (q *Queries) CreateSandboxInstance(ctx context.Context, arg CreateSandboxInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createSandboxInstance,
		arg.ID,
		arg.SandboxDefID,
		arg.WorkspaceID,
		arg.Owner,
		arg.RunAs,
		arg.ProviderSandboxID,
		arg.PolicySnapshotJson,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSeenAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, created_at) VALUES (?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createWorkspaceRef = `-- name: CreateWorkspaceRef :exec
INSERT INTO workspace_refs (workspace_id, kind, slot, ref, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateWorkspaceRefParams struct {
	WorkspaceID string
	Kind        string
	Slot        string
	Ref         string
	CreatedAt   string
}

func (q *Queries) CreateWorkspaceRef(ctx context.Context, arg CreateWorkspaceRefParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceRef,
		arg.WorkspaceID,
		arg.Kind,
		arg.Slot,
		arg.Ref,
		arg.CreatedAt,
	)
	return err
}

const getSandboxDef = `-- name: GetSandboxDef :one
SELECT id, name, provider, base_image_ref, policy_ref, created_at FROM sandbox_defs WHERE id = ?
`

func (q *Queries) GetSandboxDef(ctx context.Context, id string) (SandboxDef, error) {
	row := q.db.QueryRowContext(ctx, getSandboxDef, id)
	var i SandboxDef
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseImageRef,
		&i.PolicyRef,
		&i.CreatedAt,
	)
	return i, err
}

const getSandboxInstance = `-- name: GetSandboxInstance :one
SELECT id, sandbox_def_id, workspace_id, owner, run_as, provider_sandbox_id, policy_snapshot_json, status, created_at, updated_at, last_seen_at FROM sandbox_instances WHERE id = ?
`

func (q *Queries) GetSandboxInstance(ctx context.Context, id string) (SandboxInstance, error) {
	row := q.db.QueryRowContext(ctx, getSandboxInstance, id)
	var i SandboxInstance
	err := row.Scan(
		&i.ID,
		&i.SandboxDefID,
		&i.WorkspaceID,
		&i.Owner,
		&i.RunAs,
		&i.ProviderSandboxID,
		&i.PolicySnapshotJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, created_at FROM workspaces WHERE name = ?
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listSandboxDefs = `-- name: ListSandboxDefs :many
SELECT id, name, provider, base_image_ref, policy_ref, created_at FROM sandbox_defs ORDER BY name
`

func (q *Queries) ListSandboxDefs(ctx context.Context) ([]SandboxDef, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxDefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SandboxDef
	for rows.Next() {
		var i SandboxDef
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.BaseImageRef,
			&i.PolicyRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxInstancesByOwner = `-- name: ListSandboxInstancesByOwner :many
SELECT id, sandbox_def_id, workspace_id, owner, run_as, provider_sandbox_id, policy_snapshot_json, status, created_at, updated_at, last_seen_at FROM sandbox_instances WHERE owner = ? AND status = ? ORDER BY created_at DESC
`

type ListSandboxInstancesByOwnerParams struct {
	Owner  string
	Status string
}

func (q *Queries) ListSandboxInstancesByOwner(ctx context.Context, arg ListSandboxInstancesByOwnerParams) ([]SandboxInstance, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxInstancesByOwner, arg.Owner, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SandboxInstance
	for rows.Next() {
		var i SandboxInstance
		if err := rows.Scan(
			&i.ID,
			&i.SandboxDefID,
			&i.WorkspaceID,
			&i.Owner,
			&i.RunAs,
			&i.ProviderSandboxID,
			&i.PolicySnapshotJson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRefs = `-- name: ListWorkspaceRefs :many
SELECT workspace_id, kind, slot, ref, created_at FROM workspace_refs WHERE workspace_id = ? ORDER BY kind, slot
`

func (q *Queries) ListWorkspaceRefs(ctx context.Context, workspaceID string) ([]WorkspaceRef, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceRefs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceRef
	for rows.Next() {
		var i WorkspaceRef
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Kind,
			&i.Slot,
			&i.Ref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, created_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandboxInstanceStatus = `-- name: UpdateSandboxInstanceStatus :exec
UPDATE sandbox_instances SET status = ?, updated_at = ?, last_seen_at = ? WHERE id = ?
`

type UpdateSandboxInstanceStatusParams struct {
	Status     string
	UpdatedAt  string
	LastSeenAt sql.NullString
	ID         string
}

func (q *Queries) UpdateSandboxInstanceStatus(ctx context.Context, arg UpdateSandboxInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSandboxInstanceStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.LastSeenAt,
		arg.ID,
	)
	return err
}
